### PR TITLE
fix: add actual support for version prefixes, closes #543

### LINKED ISSUE #543: Plugin not working with release versions with prefix

### PR DESCRIPTION
**Pull request by anitvam**
#543

### CODE REVIEW

File: src/main/kotlin/org/danilopianini/gradle/gitsemver/GitSemVerExtension.kt [hunk 1]
```diff
@@ -113,7 +113,12 @@ open class GitSemVerExtension @JvmOverloads constructor(
                     if (!closestTag.buildMetadata.isEmpty()) {
                         logger.warn("Build metadata of closest tag $closestTag will be ignored.")
                     }
-                    val distance = runCommand("git", "rev-list", "--count", "$closestTag..HEAD")?.toLong()
+                    val distance = runCommand(
+                        "git",
+                        "rev-list",
+                        "--count",
+                        "${versionPrefix.get()}$closestTag..HEAD"
```
Comment (DanySK) [inline src/main/kotlin/org/danilopianini/gradle/gitsemver/GitSemVerExtension.kt:120]:
```suggestion
                        "${versionPrefix.get()}$closestTag..HEAD",
```

missing trailing comma

**Review by DanySK — APPROVED** [review]
Lovely, minor syntactic improvements at most.
